### ISSUE TITLE
Errors on Experiment.fetch()

### ISSUE THREAD

**Issue by LydGol90** [amplitude/experiment-react-native-client#9] opened 2022-02-03 09:32 UTC
Hi, we are seeing pretty regular errors from our error reporting tool when calling `Experiment.fetch`, maybe 20 or 30 a day. It isn't that clear from the error messages what the issues are and whether they are just transient server issues or real issues. Is there any documentation that might make it clearer what these issues are. Thanks!

Examples:

Android:
```
{"code":"EUNSPECIFIED","message":"java.util.concurrent.ExecutionException: java.io.InterruptedIOException: timeout","name":"Error","nativeStackAndroid":["[Object]","[Object]","[Object]","[Object]","[Object]","[Object]","[Object]","[Object]","[Object]"],"stack":"Error: java.util.concurrent.ExecutionException: java.io.InterruptedIOException: timeout\n    at promiseMethodWrapper (address at index.android.bundle:1:107722)\n    at fetch$ (address at index.android.bundle:1:2389226)\n    at call (native)\n    at tryCatch (address at index.android.bundle:1:197741)\n    at invoke (address at index.android.bundle:1:198742)\n    at anonymous (address at index.android.bundle:1:197889)\n    at call (native)\n    at tryCatch (address at index.android.bundle:1:197741)\n    at invoke (address at index.android.bundle:1:197974)\n    at anonymous (address at index.android.bundle:1:198413)\n    at tryCallTwo (/tmp/hermes/staging/hermes/cmake/intlRelease/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)\n    at doResolve (/tmp/hermes/staging/hermes/cmake/intlRelease/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)\n    at Promise (/tmp/hermes/staging/hermes/cmake/intlRelease/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)\n    at callInvokeWithMethodAndArg (address at index.android.bundle:1:198375)\n    at enqueue (address at index.android.bundle:1:198322)\n    at anonymous (address at index.android.bundle:1:197889)\n    at anonymous (address at index.android.bundle:1:200123)\n    at fetch (address at index.android.bundle:1:2389054)\n    at _callee$ (address at index.android.bundle:1:2387790)\n    at call (native)\n    at tryCatch (address at index.android.bundle:1:197741)\n    at invoke (address at index.android.bundle:1:198742)\n    at anonymous (address at index.android.bundle:1:197889)\n    at call (native)\n    at tryCatch (address at index.android.bundle:1:197741)\n    at invoke (address at index.android.bundle:1:197974)\n    at anonymous (address at index.android.bundle:1:198186)\n    at tryCallOne (/tmp/hermes/staging/hermes/cmake/intlRelease/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)\n    at anonymous (/tmp/hermes/staging/hermes/cmake/intlRelease/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)\n    at apply (native)\n    at anonymous (address at index.android.bundle:1:204471)\n    at _callTimer (address at index.android.bundle:1:203370)\n    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:203574)\n    at callReactNativeMicrotasks (address at index.android.bundle:1:205556)\n    at __callReactNativeMicrotasks (address at index.android.bundle:1:111225)\n    at anonymous (address at index.android.bundle:1:110311)\n    at __guard (address at index.android.bundle:1:111066)\n    at flushedQueue (address at index.android.bundle:1:110222)\n    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:110165)"}
```

iOS: 
```
{"code":"Error in fetch","domain":"NSURLErrorDomain","message":"Optional(Error Domain=NSURLErrorDomain Code=-1001 \"The request timed out.\" UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x281f07e40 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 \"(null)\" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <A0694FE8-9648-4C39-B052-2776ED25DF6F>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(\n    \"LocalDataTask <A0694FE8-9648-4C39-B052-2776ED25DF6F>.<1>\"\n), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://api.lab.amplitude.com/sdk/vardata, NSErrorFailingURLKey=https://api.lab.amplitude.com/sdk/vardata, _kCFStreamErrorDomainKey=4})","name":"Error","nativeStackIOS":["0   Uptime                              0x00000001002be214 _ZN8facebook5react11JSIExecutor21defaultTimeoutInvokerERKNSt3__18functionIFvvEEENS3_IFNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEvEEE + 284868","1   Uptime                              0x000000010028fb18 _ZN8facebook5react11JSIExecutor21defaultTimeoutInvokerERKNSt3__18functionIFvvEEENS3_IFNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEvEEE + 94664","2   Uptime                              0x0000000100443c80 __cxa_throw + 387812","3   Uptime                              0x0000000100446ab4 __cxa_throw + 399640","4   Uptime                              0x0000000100443a10 __cxa_throw + 387188","5   Uptime                              0x00000001000c50b4 Uptime + 118964","6   Uptime                              0x00000001000c5010 Uptime + 118800","7   Uptime                              0x00000001000c497c Uptime + 117116","8   Uptime                              0x00000001000c2974 Uptime + 108916","9   Uptime                              0x00000001000c2e30 Uptime + 110128","10  CFNetwork                           0x0000000183e840ac CFURLRequestSetMainDocumentURL + 3028","11  CFNetwork                           0x0000000183e95054 _CFNetworkErrorCopyLocalizedDescriptionWithHostname + 11444","12  libdispatch.dylib                   0x0000000183352924 EDD169E1-D0DB-3808-A19E-99C1CD5A1C4C + 10532","13  libdispatch.dylib                   0x0000000183354670 EDD169E1-D0DB-3808-A19E-99C1CD5A1C4C + 18032","14  libdispatch.dylib                   0x000000018335bdf4 EDD169E1-D0DB-3808-A19E-99C1CD5A1C4C + 48628","15  libdispatch.dylib                   0x000000018335c99c EDD169E1-D0DB-3808-A19E-99C1CD5A1C4C + 51612","16  libdispatch.dylib                   0x00000001833671b8 EDD169E1-D0DB-3808-A19E-99C1CD5A1C4C + 94648","17  libsystem_pthread.dylib             0x00000001f2f630f4 _pthread_wqthread + 288","18  libsystem_pthread.dylib             0x00000001f2f62e94 start_wqthread + 8"],"stack":"Error: Optional(Error Domain=NSURLErrorDomain Code=-1001 \"The request timed out.\" UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x281f07e40 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 \"(null)\" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <A0694FE8-9648-4C39-B052-2776ED25DF6F>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(\n    \"LocalDataTask <A0694FE8-9648-4C39-B052-2776ED25DF6F>.<1>\"\n), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://api.lab.amplitude.com/sdk/vardata, NSErrorFailingURLKey=https://api.lab.amplitude.com/sdk/vardata, _kCFStreamErrorDomainKey=4})\n    at promiseMethodWrapper (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:3182:45)\n    at fetch$ (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:209453:82)\n    at call (native)\n    at tryCatch (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:10929:23)\n    at invoke (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11099:32)\n    at anonymous (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:10971:30)\n    at call (native)\n    at tryCatch (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:10929:23)\n    at invoke (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11001:30)\n    at anonymous (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11031:19)\n    at tryCallTwo (/Users/distiller/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:61:9)\n    at doResolve (/Users/distiller/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:216:25)\n    at Promise (/Users/distiller/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:82:14)\n    at callInvokeWithMethodAndArg (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11030:33)\n    at enqueue (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11035:157)\n    at anonymous (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:10971:30)\n    at anonymous (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11050:69)\n    at fetch (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:209443:40)\n    at _callee$ (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:209321:94)\n    at call (native)\n    at tryCatch (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:10929:23)\n    at invoke (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11099:32)\n    at anonymous (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:10971:30)\n    at call (native)\n    at tryCatch (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:10929:23)\n    at invoke (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11001:30)\n    at anonymous (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11011:21)\n    at tryCallOne (/Users/distiller/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:53:16)\n    at anonymous (/Users/distiller/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:139:27)\n    at apply (native)\n    at anonymous (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11680:26)\n    at _callTimer (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11590:17)\n    at _callReactNativeMicrotasksPass (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11619:17)\n    at callReactNativeMicrotasks (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11825:44)\n    at __callReactNativeMicrotasks (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:3509:46)\n    at anonymous (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:3384:45)\n    at __guard (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:3492:15)\n    at flushedQueue (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:3383:21)\n    at invokeCallbackAndReturnFlushedQueue (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:3376:33)","userInfo":{"NSErrorFailingURLKey":null,"NSErrorFailingURLStringKey":"https://api.lab.amplitude.com/sdk/vardata","NSLocalizedDescription":"The request timed out.","NSUnderlyingError":"[Object]","_NSURLErrorFailingURLSessionTaskErrorKey":"LocalDataTask <A0694FE8-9648-4C39-B052-2776ED25DF6F>.<1>","_NSURLErrorRelatedURLSessionTaskErrorKey":"[Array]","_kCFStreamErrorCodeKey":-2102,"_kCFStreamErrorDomainKey":4}}
```

```
{"code":"Error in fetch","domain":"AmplitudeExperiment.ExperimentError","message":"Optional(AmplitudeExperiment.ExperimentError(message: \"Error Response: status=502\"))","name":"Error","nativeStackIOS":["0   Uptime                              0x0000000102c46214 _ZN8facebook5react11JSIExecutor21defaultTimeoutInvokerERKNSt3__18functionIFvvEEENS3_IFNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEvEEE + 284868","1   Uptime                              0x0000000102c17b18 _ZN8facebook5react11JSIExecutor21defaultTimeoutInvokerERKNSt3__18functionIFvvEEENS3_IFNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEvEEE + 94664","2   Uptime                              0x0000000102dcbc80 __cxa_throw + 387812","3   Uptime                              0x0000000102dceab4 __cxa_throw + 399640","4   Uptime                              0x0000000102dcba10 __cxa_throw + 387188","5   Uptime                              0x0000000102a4d0b4 Uptime + 118964","6   Uptime                              0x0000000102a4d010 Uptime + 118800","7   Uptime                              0x0000000102a4c97c Uptime + 117116","8   Uptime                              0x0000000102a4acc4 Uptime + 109764","9   Uptime                              0x0000000102a4ae30 Uptime + 110128","10  CFNetwork                           0x00000001814030ac CFURLRequestSetMainDocumentURL + 3028","11  CFNetwork                           0x0000000181414054 _CFNetworkErrorCopyLocalizedDescriptionWithHostname + 11444","12  libdispatch.dylib                   0x00000001808d1924 EDD169E1-D0DB-3808-A19E-99C1CD5A1C4C + 10532","13  libdispatch.dylib                   0x00000001808d3670 EDD169E1-D0DB-3808-A19E-99C1CD5A1C4C + 18032","14  libdispatch.dylib                   0x00000001808dadf4 EDD169E1-D0DB-3808-A19E-99C1CD5A1C4C + 48628","15  libdispatch.dylib                   0x00000001808db99c EDD169E1-D0DB-3808-A19E-99C1CD5A1C4C + 51612","16  libdispatch.dylib                   0x00000001808e61b8 EDD169E1-D0DB-3808-A19E-99C1CD5A1C4C + 94648","17  libsystem_pthread.dylib             0x00000001f16370f4 _pthread_wqthread + 288","18  libsystem_pthread.dylib             0x00000001f1636e94 start_wqthread + 8"],"stack":"Error: Optional(AmplitudeExperiment.ExperimentError(message: \"Error Response: status=502\"))\n    at promiseMethodWrapper (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:3182:45)\n    at fetch$ (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:209453:82)\n    at call (native)\n    at tryCatch (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:10929:23)\n    at invoke (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11099:32)\n    at anonymous (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:10971:30)\n    at call (native)\n    at tryCatch (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:10929:23)\n    at invoke (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11001:30)\n    at anonymous (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11031:19)\n    at tryCallTwo (/Users/distiller/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:61:9)\n    at doResolve (/Users/distiller/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:216:25)\n    at Promise (/Users/distiller/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:82:14)\n    at callInvokeWithMethodAndArg (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11030:33)\n    at enqueue (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11035:157)\n    at anonymous (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:10971:30)\n    at anonymous (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11050:69)\n    at fetch (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:209443:40)\n    at _callee$ (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:209321:94)\n    at call (native)\n    at tryCatch (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:10929:23)\n    at invoke (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11099:32)\n    at anonymous (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:10971:30)\n    at call (native)\n    at tryCatch (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:10929:23)\n    at invoke (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11001:30)\n    at anonymous (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11011:21)\n    at tryCallOne (/Users/distiller/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:53:16)\n    at anonymous (/Users/distiller/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:139:27)\n    at apply (native)\n    at anonymous (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11680:26)\n    at _callTimer (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11590:17)\n    at _callReactNativeMicrotasksPass (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11619:17)\n    at callReactNativeMicrotasks (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:11825:44)\n    at __callReactNativeMicrotasks (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:3509:46)\n    at anonymous (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:3384:45)\n    at __guard (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:3492:15)\n    at flushedQueue (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:3383:21)\n    at invokeCallbackAndReturnFlushedQueue (/Users/distiller/Library/Developer/Xcode/DerivedData/Uptime-dkpaxdhuvwzwhrctuxmdbmpzmuxu/Build/Intermediates.noindex/ArchiveIntermediates/Uptime-prod/BuildProductsPath/Release-iphoneos/main.jsbundle:3376:33)","userInfo":{}}
```

**Comment by bgiori** [comment] 2022-02-08 18:42
Hi @LydGol90 thanks for reporting this issue!

Looking into this now and will get back to you here ASAP.

**Comment by bgiori** [comment] 2022-02-15 01:20
@LydGol90 Just wanted to check something, are these errors crashing your application or simply logged to your reporting tool?

I ask because based on the error messages, the errors seem to be due to http errors and timeouts on `fetch()`. Based on the code, errors caused by failed fetch requests should be returned as a rejected promise. 

That said, we are currently working to make our evaluation servers more robust during deployment to cut down on 50X errors. 

As for the timeouts, this may simply be due to spotty internet connection.

**Comment by LydGol90** [comment] 2022-02-15 14:50
@bgiori No these are not crashes just error logging. I was just surprised at the volumes we were getting.

**Comment by bgiori** [comment] 2022-02-15 17:31
@LydGol90 Are you using a customer configuration for `fetchTimeoutMillis`? The default value is 10 seconds which should be plenty of time unless the user's internet connection is very spotty.

**Comment by LydGol90** [comment] 2022-02-16 16:24
@bgiori Nope we are not setting that value so must be the 10s default. I have just seen the `retryFetchOnFailure` option. Is that defaulted to true or false? If you don't see anything suspicious with these errors and you are working on making servers more robust then I am not too worried.

**Comment by bgiori** [comment] 2022-02-16 17:23
Default `retryFetchOnFailure` value is `true`, those retries will happen in the background, though, after the promise is rejected. 

>  If you don't see anything suspicious with these errors and you are working on making servers more robust then I am not too worried.

I'll close this ticket then. Thanks again for reporting this!

**Closed by bgiori** 2022-02-16 17:23 UTC
